### ISSUE TITLE
Every day a new release (without any real changes)

### ISSUE THREAD

**Issue by ksarink** [bitnami/bitnami-docker-ejbca#13]
Hey,

I noticed that the bitnami-bot creates a commit every day with a new release and a new tag. Also, these updates are pushed to the docker hub every day. It's really hard to find out if there is a need to update the docker container since the hashes differ. Is it possible to change this behaviour?

**Comment by beltran-rubo** [comment]
Thanks @ksarink,

Bitnami releases those images daily to make sure we have the latest package available from the OS and to reduce the CVEs. 

Note the policy for the [Helm Chart for EJBCA](https://github.com/bitnami/charts/tree/master/bitnami/ejbca) is only upgraded whenever there is a new version of EJBCA, if there is any CVE fixed by the OS or if there is any configuration change.

**Comment by ksarink** [comment]
@beltran-rubo I didn't think of that, thanks for explaining. It's a very usefull feature.
